version: '3.8'

services:
  app-monitor:
    image: app-monitor-api:latest
    container_name: app_monitor_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production